### ISSUE TITLE
Ability to see OpenAI "Typing"

### ISSUE THREAD

**Issue by andrewgazelka** [getcollective-ai/collective#78]
We should have some notion of `diff` packets (maybe it could be called something else) where packets give a differential instead of just a single response.

For instance the question packet

https://github.com/getcollective-ai/collective/blob/3402a5c15ad251d1854b4eaa4998470d51e2f2c3/code/protocol/src/server.rs#L4-L8

in my opinion should show GPT4 "typing". 

We would potentially have the same `PacketId` but just accumulate data:
https://github.com/getcollective-ai/collective/blob/2996496ee6e5ece1826d3d0b57daca9c1d97a351/code/protocol/src/lib.rs#L13-L17

For instance, if we execute `cargo run -p frontend-cli`

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/7644264/232365583-d4e043ad-0345-46f0-9171-1a0f4a01c75b.png">

We should be able to see GPT4 typing 

- Wh
- What
- What ty
- What type of
- ...

---

This is possible via 

https://github.com/andrewgazelka/tokio-openai/blob/main/src/lib.rs#L542-L545

**Comment by gabrieldemian** [comment]
done
